version: "3"

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./app:/app/app"
      - "./scripts/prestart.sh:/app/prestart.sh"
    environment:
      DB_HOST: db
      DB_USER: mysql
      DB_PASSWORD: password
      DB_NAME: sample
      LOG_LEVEL: info
      APP_LOG_LEVEL: DEBUG
    command: "/start-reload.sh"
    networks:
      - app_net

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./local_db/init:/docker-entrypoint-initdb.d
      - ./local_db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./local_db/data:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net:
