version: 0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ${TASK_DEF_ARN}
        LoadBalancerInfo:
          ContainerName: app
          ContainerPort: 80
