version: "3"

services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      LOG_LEVEL: error # uvicornのログレベル
      APP_LOG_LEVEL: ${APP_LOG_LEVEL} # FastAPIのログレベル
    ports:
      - "80:80"
    logging:
      driver: awsfirelens
      options:
        Name: firehose
        region: ap-northeast-1
        delivery_stream: firelens-${SYSTEM_NAME}-stream

  log_router:
    image: 906394416424.dkr.ecr.ap-northeast-1.amazonaws.com/aws-for-fluent-bit:2.1.1
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/${SYSTEM_NAME}
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: firelens
