version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ${TASK_EXE_ROLE_ARN}
  task_role_arn: ${TASK_ROLE_ARN}
  services:
    app:
      essential: true
    log_router:
      essential: false
      firelens_configuration:
        type: fluentbit
        options:
          enable-ecs-log-metadata: "true"

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - ${SUBNET_AZ1}
        - ${SUBNET_AZ2}
      security_groups:
        - ${SECURITY_GROUP_DEFAULT}
  task_placement:
    strategy:
      - type: spread
        field: instanceId
