variable "system_name" {}
variable "vpc_id" {}
variable "subnet" {}
variable "access_logs_bucket" {}
variable "application_logs_bucket" {}
variable "certificate_arn" {}
variable "default_security_group" {}
variable "autoscaling_config" {}
variable "ec2_config" {}
variable "key_pair" {}
